### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#112]
I deployed a new AKS cluster and cannot communicate to the new cluster.
I get the error: Unable to connect to the server: net/http: TLS handshake timeout

Any issues?

**Comment by bramvdklinkenberg** [comment]
Deleted the cluster and tried deploying it again and get the same error.

**Comment by kwe** [comment]
I'm also getting this on a previously created cluster

**Comment by hairmare** [comment]
It looks like the managed control plane  is having issues. I'm seeing the same problem on both existing AKS deployments and new clusters in the westeurope region. The nodes in the cluster cannot connect to the API as well (as seen in the log files on a node). Please let us know if you need more info to debug/fix this!

**Comment by jakobli** [comment]
seeing the same

**Comment by hairmare** [comment]
@jakobli I had the same error earlier today and it resolved itself when I reran the update (`az aks get-versions` doesn't show any updates after running the upgrade the second time).

I wasn't able to connect to the control plane before or after the update. I looks like the control plane issues aren't specific to the installed k8s version.

**Comment by seniorquico** [comment]
I just encountered this error on an existing cluster, already upgraded to the latest available version. I followed slack's advice from https://github.com/Azure/AKS/issues/14#issuecomment-352925628, just re-running the upgrade command. I can now connect to my cluster as expected.

**Comment by bramvdklinkenberg** [comment]
Hmm, will give a try again tomorrow. Replaced the aks cluster with an acs cluster.
Aks is to unstable.

**Comment by kwe** [comment]
re-running upgrade does not work for me :-(

**Comment by jakobehn** [comment]
I'm seeing the same thing, creating clusters work fine (using the 2.0.21 version),  but can't connect to it afterwards.

**Comment by jakobli** [comment]
Which region is everyone using? For me it's failing in WestEurope

**Comment by kwe** [comment]
yes, West Europe for me also

**Comment by avaranovich** [comment]
same here, westeurope

**Comment by jakobehn** [comment]
Also west europe. Just tried creating a cluster in the eastus region and that seems to work fine

**Comment by johnhamelink** [comment]
I'm also experiencing this issue. Attempting to upgrade to 1.8.2 to see if this fixes the handshake timeout.

**Comment by rakeshv1** [comment]
I am seeing the same thing in westeurope and eastus  
`Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by kwe** [comment]
for me, I 'nuked it from space' - deleted the resource group and recreated (still in westeurope). It all works again. Obviously, it's a preview, but this was scary.

**Comment by johnhamelink** [comment]
@kwe I can confirm I was able to connect via kubectl after deleting the cluster & resource group and recreating, then waiting until the "creating..." bar had disappeared in the AKS overview section of Azure Console. It took around 10 minutes for this to happen.

**Comment by razi-rais** [comment]
I also had the same issue and simply deleting and recreating the cluster does not the problem. What did fix the issue was removal of --dns-name-prefix parameter from the az aks create command. Here are both not-working and working commands:

**Not working (Error'd)**
`az aks create --resource-group rz-aks-rg --name rz-aks-cluster --node-count 1 --node-vm-size "Standard_A2"  --generate-ssh-keys  --dns-name-prefix rzaks1`


**Working (--dns-name-prefix parameter is removed)**
`az aks create --resource-group rz-aks-rg --name rz-aks-cluster --node-count 1 --node-vm-size "Standard_A2"  --generate-ssh-keys  `

**Comment by apryiomka** [comment]
I started having this issue on the existing cluster.

**Comment by bramvdklinkenberg** [comment]
It should be working again. I got a reply from microsoft that the masters that azure hosts were having problems with getting all services running within a timely manner.

**Comment by apryiomka** [comment]
The issue absolutely has NOT been resolved and still persists!

**Comment by squillace** [comment]
@apryiomka yeah, was having the same issue with West EU today.  Try again; there is an ongoing investigation here.

**Comment by dzoech** [comment]
Had the same problem right now with West Europe and 1.7.7. Deleted and recreated the cluster with version 1.8.1 and now it's working.

**Comment by wittry** [comment]
I encounter this same issue with a 1.7.9 aks cluster created a few weeks ago in centralUS that had been working fine. I didn't want to upgrade but used "az aks upgrade" and specified the current cluster version to rebuild all the nodes with any OS image updates and that resolved it for me.

**Comment by kvolkovich-sc** [comment]
The same issue at westeurope

**Comment by omgsarge** [comment]
same issue West Europe, our problem appeared yesterday - it appeared after we had a pod which was stuck in a back-off loop, still cannot connect to it now

**Comment by seniorquico** [comment]
We had a node completely disconnect from our cluster. Coincidentally (or not), this error is now also reoccurring for us. Our cluster is in East US.

**Comment by asos-tonygorman** [comment]
Also started having this issue on Friday (13 April 18). West Europe

**Comment by mollyporph** [comment]
Started having the same issue today (18th of april) on west europe.

**Comment by omgsarge** [comment]
MS on-call managed to restore our AKS instance to the correct state, it was a good excuse to test out our DR release scripting though! 👍

**Comment by pabSec** [comment]
Started having the same issue from 24th April 18. Central US

**Comment by seniorquico** [comment]
We had another cluster go down on Apr 22 in East US. (We had just worked through a down cluster on Apr 5 in East US.) Microsoft support confirmed yesterday there was an infrastructure problem and it had been resolved. Not sure if that applies to other regions. None of the tricks we've collected on GitHub worked this time (e.g. trying to re-run an upgrade to the current version). It sure would be nice if there were better communication on this issue... opening support tickets to essentially get back a "closed as resolved" status is starting to become frustrating.

**Comment by rustc0h1e** [comment]
exact same issue here. 
now, am i supposed to tear down the cluster and recreate another one or is this fixable or what ?

**Comment by itsMicah** [comment]
Yeah, I having the same issue here! Help!

**Comment by debroyv** [comment]
Same issue with us too (our region is East US) - we understand that AKS is still in preview, but it is very frustrating when one has to try things like re-creating a cluster or attempting an upgrade, just to see if it works (which for the record it didn't).

**Comment by mkfsn** [comment]
Same issue here in East US with a 1.7.7 and a 1.9.2 aks cluster.

**Comment by goudarzi** [comment]
++

**Comment by giorgited** [comment]
recreating works but its so annoying when you have complex setup

**Comment by necevil** [comment]
Seems like this one is still occurring.
We run two Clusters one for staging, one for production.
Production is un-reachable but Staging — which is essentially a mirror right now (also in U.S. East) — can be connected to as normal.

**Comment by necevil** [comment]
@giorgited @goudarzi @mkfsn @debroyv @itsMicah @rustc0h1e @seneccamiller @seniorquico @pabSec @omgsarge @kvolkovich-sc @wittry @dzoech @squillace @apryiomka @razi-rais @apryiomka @johnhamelink @kwe @jakobehn @avaranovich  
I am starting to collect info on this issue in a question over on StackOverflow:
https://stackoverflow.com/questions/50726534/why-cant-kubectl-connect-to-the-azure-aks-server-managing-my-cluster-net-http

If you guys could answer a couple of these (here or above on SOF)
-------------

1. Have you had the TLS issue impact your Clusters more than once?
2. How long did it take before your Cluster was back up and could be connected to (what was the outage duration)?
3. Did it 'heal' itself / resolve / come back to life on it's own or did you have to post a support ticket — and wait for MS to fix it?
4. If support, how long was that ticket posted for before the problem was solved on your Cluster?
5. Did you notice anything weird with your CPU / Network IO dropping but your disk usage jumping higher? (see my metrics on stackoverflow)
6. Would you be in favor of allowing AKS preview customers to create higher Severity Help Tickets (For this specific issue only) regardless of their support plan in order to achieve a more timely solution?

Feel free to respond here or (as mentioned) hit StackOverflow and I will collect the responses.

**Comment by omgsarge** [comment]
No way that this problem is resolved, it's like a sword of damocles and a blocker to us adopting AKS in production (as well as general availability, but if AKS was stable even in preview I would consider it) 

Our experience:

Q. Have you had the TLS issue impact your Clusters more than once?

Yep. We are onto our 7th AKS instance due to recreation each time, as the process for getting a corrupt one back running takes variable amount of time (4+ days). 

Q. How long did it take before your Cluster was back up and could be connected to (what was the outage duration)?

4-6 days, two clusters never came back. 

Q. Did it 'heal' itself / resolve / come back to life on it's own or did you have to post a support ticket — and wait for MS to fix it?

Post ticket, wait for fix. 

Q. If support, how long was that ticket posted for before the problem was solved on your Cluster?

As above, 4-6 days, in some cases never. 

Q. Did you notice anything weird with your CPU / Network IO dropping but your disk usage jumping higher? (see my metrics on stackoverflow)

Not specifically checked but will do next time this happens. 

Q. Would you be in favor of allowing AKS preview customers to create higher Severity Help Tickets (For this specific issue only) regardless of their support plan in order to achieve a more timely solution?

Yes, though a permanent fix would obviously be great. For me it's the unknown root cause that bothers me most. 


We ended up scripting our entire environment to recreate on click of a button - spanning Web apps, apis, dbs, auto dns, let's encrypt, etc simply because they were randomly dying. No bad thing but a shame to have to do it due to reliability issues.

Scaling (up or down) as well as upgrading cluster versions did nothing in our case, it was typically just dead from being able to connect to the master.

**Comment by necevil** [comment]
@omgsarge interested in the metrics the next go round, not that it's a solution but who knows, might be able to alarm off of it as opposed to just attempting to kubectl and finding out that's not an option.

It seems like most people have experienced it more than once, I am wondering if maybe the fact that our services (on the effected Cluster) occupied so little of the VM's resources kept them alive or whether that happens for others.

It sounds like your stuff just crashed as soon as the issue presented itself?

Added your experience that scaling up / down DID NOT work to the answer on StackOverflow.  Will be adding another answer which will be a concatenation of the info people decide to post regarding how long this stuff takes and how often it happens.

Thanks for the post.
Would love to hear more from others who have been impacted.

**Comment by necevil** [comment]
Just an update on my situation (post mortem) which I just finished adding to StackOverflow docs (https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect).   Added my 'recovered' utilization metrics over there.

After implementing the scale nodes up / back down my Metric (CPU utilization and Network IO) went back to normal meaning that this issue 99% was responsible for that change.

It also means that you can likely ALARM for the issue assuming that your App / Service doesn't have huge spikes and maintains relatively consistent usage.  If if the app / service has more erratic unpredictable usage it is probably possible to do some more advanced maths and develop an Alarm that would accurately predict the occurrence of this issue.

That may be over my head but I will post back (and on StackOverflow)  if I can figure out an alarm that works reliably in low utilization volatility instances.

**Comment by hsmiranda** [comment]
i'm resolved this problem with setting proxy variables correct, oc, az or kubectl utilize proxy variables for connect to api even on localhost or remote connection.
