### ISSUE TITLE
Nodes have incorrect failure-domain.beta.kubernetes.io/zone label after upgrade

### ISSUE THREAD

**Issue by jdamata** [Azure/AKS#1337]
**What happened**:
Upgraded AKS cluster from 1.14.6 to 1.14.8.

Pods are unable to mount PVCs because the node and label are mismatched

$ kubectl get nodes --show-labels | grep aks-f8spool1-11432044-vmss000000
aks-f8spool1-11432044-vmss000000   Ready                      agent   54d   v1.14.8   agentpool=f8spool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_F8s,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eastus2,**failure-domain.beta.kubernetes.io/zone=eastus2-2**,kubernetes.azure.com/cluster=MC_rg-us-en-aks-phobos_phobos_eastus2,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-f8spool1-11432044-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS

![Screen Shot 2019-11-27 at 12 32 17 PM](https://user-images.githubusercontent.com/33775101/69746315-f9209600-1111-11ea-9958-c03e5cca4faa.png)

**What you expected to happen**:
During AKS upgrades, either nodes should remain in the same AZ or the label should be corrected.

**How to reproduce it (as minimally and precisely as possible)**:
Create pvcs and mount to a workload
Upgrad AKS cluster from 1.14.6 to 1.14.8.

**Comment by bbgobie** [comment]
Watching this

**Comment by jluk** [comment]
@jdamata do you have a support ticket number you can share? If not could you please open one?

cc @JunSun17

**Comment by jdamata** [comment]
> @jdamata do you have a support ticket number you can share? If not could you please open one?
> 
> cc @JunSun17

119112624005495

**Comment by jluk** [comment]
Thank you our engineers are investigating and we can use the support ticket for latest findings. I'll leave this issue open until the ticket is resolved.

**Comment by gurrish** [comment]
I also ran into this problem after adding a second node pool with three availability zones
`Node Affinity:
  Required Terms:
    Term 0:        failure-domain.beta.kubernetes.io/region in [westeurope]
                   **failure-domain.beta.kubernetes.io/zone in [westeurope-1**]`

`Labels:
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_DS3_v2
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=westeurope
                    **failure-domain.beta.kubernetes.io/zone=0**`

**Comment by jdamata** [comment]
I didn't experience this problem with upgrading to 1.15.7

Maybe this has been fixed and can be closed

**Comment by jluk** [comment]
@jdamata confirmed we have a fix for this. It should be releasing starting next week on release 2020-13-01

**Comment by psalaberria002** [comment]
How is this closed? I had the exact same issue in 1.14.8, and after upgrading to 1.15.7 I am still seeing inconsistencies in the labels. Some pools have `failure-domain.beta.kubernetes.io/zone=<number>` whereas others have `failure-domain.beta.kubernetes.io/zone=<region>-<number>`.

PV tolerations seem to be immutable. How can I solve this issue?

**Comment by psalaberria002** [comment]
I tried creating the pool via Terraform instead of using the UI, and the nodes now have the correct label.

**Comment by 617m4rc** [comment]
We are facing similar problems after upgrading to version 1.15.10. Our node pools are created via Terraform. Did anyone find a solution that ensures consistent labeling of worker nodes and PVCs? In particular, we are facing inconsistencies with our custom storage classes using the azure-disk provisioner.

```
kubectl describe nodes | grep -e "Name:" -e "failure-domain.beta.kubernetes.io/zone"

Name:               aks-default-xxx-0
                    failure-domain.beta.kubernetes.io/zone=westeurope-1
Name:               aks-default-xxx-1
                    failure-domain.beta.kubernetes.io/zone=westeurope-2
Name:               aks-default-xxx-2
                    failure-domain.beta.kubernetes.io/zone=westeurope-1
Name:               aks-default-xxx-3
                    failure-domain.beta.kubernetes.io/zone=westeurope-2
Name:               aks-default-xxx-4
                    failure-domain.beta.kubernetes.io/zone=westeurope-1
Name:               aks-default-xxx-5
                    failure-domain.beta.kubernetes.io/zone=westeurope-3
Name:               aks-default-xxx-6
                    failure-domain.beta.kubernetes.io/zone=westeurope-2
Name:               aks-default-xxx-7
                    failure-domain.beta.kubernetes.io/zone=westeurope-3
```

```
kubectl describe sc test-sc

Name:            test-sc
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"test","helm-release":"test"},"name":"test-sc"},"parameters":{"kind":"shared","storageaccounttype":"Standard_LRS"},"provisioner":"kubernetes.io/azure-disk","volumeBindingMode":"WaitForFirstConsumer"}

Provisioner:           kubernetes.io/azure-disk
Parameters:            kind=shared,storageaccounttype=Standard_LRS
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```

```
kubectl describe pv pvc-xxx -n test

Name:              pvc-xxx
Labels:            <none>
Annotations:       pv.kubernetes.io/bound-by-controller: yes
                   pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
                   volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      test-sc
Status:            Bound
Claim:             test/data-volume-xxx
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          10Gi
Node Affinity:
  Required Terms:
    Term 0:        failure-domain.beta.kubernetes.io/region in [westeurope]
                   failure-domain.beta.kubernetes.io/zone in [0]
    Term 1:        failure-domain.beta.kubernetes.io/region in [westeurope]
                   failure-domain.beta.kubernetes.io/zone in [1]
    Term 2:        failure-domain.beta.kubernetes.io/region in [westeurope]
                   failure-domain.beta.kubernetes.io/zone in [2]
Message:
Source:
    Type:         AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)
    DiskName:     kubernetes-dynamic-pvc-xxx
    DiskURI:      https://xxx
    Kind:         Shared
    FSType:
    CachingMode:  ReadOnly
    ReadOnly:     false
Events:           <none>
```

**Comment by jluk** [comment]
A previous fix was made to address this, but it's possible the issue was not resolved. Re-opening so we can take a look.

**Comment by jluk** [comment]
@617m4rc can you open a support ticket and share the request number here? We're trying to reproduce the problem, but enabling our SRE team to investigate the cluster itself will help.

**Comment by 617m4rc** [comment]
@jluk We have opened support ticket 120032424001655. In the meantime, we already found out that node affinity rules vary between format $region-$number and the purely numerical format $number, depending on the kind of storage class used. Is it the expected behavior that there is a difference between storage classes of kind Shared and the ones of kind Managed?

```
kubectl describe pv pvc-xxx

Name: pvc-xxx
Labels: failure-domain.beta.kubernetes.io/region=westeurope
{{ failure-domain.beta.kubernetes.io/zone=westeurope-1}}
Annotations: pv.kubernetes.io/bound-by-controller: yes
{{ pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk}}
{{ volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner}}
Finalizers: [kubernetes.io/pv-protection]
StorageClass: test-westeurope-1-fast
Status: Bound
Claim: test/data-volume-xxx
Reclaim Policy: Delete
Access Modes: RWO
VolumeMode: Filesystem
Capacity: 10Gi
Node Affinity:
Required Terms:
Term 0: failure-domain.beta.kubernetes.io/region in [westeurope]
failure-domain.beta.kubernetes.io/zone in [westeurope-1]
Message:
Source:
{{ Type: AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)}}
{{ DiskName: kubernetes-dynamic-pvc-xxx}}
{{ DiskURI: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-xxx}}
Kind: Managed
{{ FSType:}}
{{ CachingMode: ReadOnly}}
{{ ReadOnly: false}}
Events: <none>
```

```
kubectl describe pv pvc-yyy

Name: pvc-yyy
Labels: <none>
Annotations: pv.kubernetes.io/bound-by-controller: yes
{{ pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk}}
{{ volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner}}
Finalizers: [kubernetes.io/pv-protection]
StorageClass: test-shared-westeurope-1-fast
Status: Bound
Claim: test-shared/data-volume-yyy
Reclaim Policy: Delete
Access Modes: RWO
VolumeMode: Filesystem
Capacity: 10Gi
Node Affinity:
{{ Required Terms:}}
Term 0: failure-domain.beta.kubernetes.io/region in [westeurope]
failure-domain.beta.kubernetes.io/zone in [0]
Term 1: failure-domain.beta.kubernetes.io/region in [westeurope]
failure-domain.beta.kubernetes.io/zone in [1]
Term 2: failure-domain.beta.kubernetes.io/region in [westeurope]
failure-domain.beta.kubernetes.io/zone in [2]
Message:
Source:
{{ Type: AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)}}
{{ DiskName: kubernetes-dynamic-pvc-yyy}}
{{ DiskURI: https://yyy/vhds/kubernetes-dynamic-pvc-yyy}}
Kind: Shared
{{ FSType:}}
{{ CachingMode: ReadOnly}}
{{ ReadOnly: false}}
Events: <none>
```

**Comment by jorge-aguas** [comment]
Can confirm. Failure zone labels for nodes with AZs don't match affinity requirements of azure-disk:shared type of PVs:

```
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ cat repro.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
  name: sharedtest
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharedtest-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sharedtest
  resources:
    requests:
      storage: 10Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: testpvcs
spec:
  containers:
  - name: testpvcs
    image: nginx:latest
    volumeMounts:
    - mountPath: "/mnt/shared"
      name: shared
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: sharedtest-pvc

aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ 
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ 
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ az aks get-credentials -g reprous -n testzones
The behavior of this command has been altered by the following extension: aks-preview
Merged "testzones" as current context in /home/aguasj/.kube/config
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ kubectl apply -f repro.yaml 
storageclass.storage.k8s.io/sharedtest created
persistentvolumeclaim/sharedtest-pvc created
pod/testpvcs created
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ kubectl describe pod testpvcs | tail -n 1
  Warning  FailedScheduling  30s   default-scheduler  0/1 nodes are available: 1 node(s) had volume node affinity conflict.
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
pvc-8a4975c3-aebf-4a01-a5de-bb566ec47377   10Gi       RWO            Delete           Bound    default/sharedtest-pvc   sharedtest              55s
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ kubectl describe pv pvc-8a4975c3-aebf-4a01-a5de-bb566ec47377 | grep -A7 Affinity
Node Affinity:     
  Required Terms:  
    Term 0:        failure-domain.beta.kubernetes.io/region in [eastus2]
                   failure-domain.beta.kubernetes.io/zone in [0]
    Term 1:        failure-domain.beta.kubernetes.io/region in [eastus2]
                   failure-domain.beta.kubernetes.io/zone in [1]
    Term 2:        failure-domain.beta.kubernetes.io/region in [eastus2]
                   failure-domain.beta.kubernetes.io/zone in [2]
aguasj@JOAGUAS-BOOK2:~/repro/diskPvc$ kubectl describe nodes | egrep 'Name:|failure'
Name:               aks-nodepool1-30283348-vmss000000
                    failure-domain.beta.kubernetes.io/region=eastus2
                    failure-domain.beta.kubernetes.io/zone=eastus2-1

```
Should work with nodes with no AZs as label failure-domain.beta.kubernetes.io/zone would just be **n** as required by pv

**Comment by 617m4rc** [comment]
Thanks for the confirmation. The question of whether this is the expected behavior or a bug remains open. Can anyone comment on this?

**Comment by MarcosMMartinez** [comment]
We have another hit on: 120041421002219

**Comment by bcorijn** [comment]
Yeah, just hit this too on a node pool created manually in UI. My previously created terraform nodepools do work correctly...

**Comment by marko-k0** [comment]
This is a big issue for us as well. We were at 1.14.8 and upgraded to 1.15.10 and that did not resolve the issue. Then we upgraded to 1.16.9 and that didn't make a difference as well. It seems that the primary node pool has the right labels but any additional node pool has `failure-domain.beta.kubernetes.io/zone=<num>`.

**Comment by andyzhangx** [comment]
pls add `volumeBindingMode: WaitForFirstConsumer` in azure disk storage class for zoned VMSS cluster.

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/using-availability-zones.md#node-labels
```
Both zoned and unzoned nodes are supported, but the value of node label failure-domain.beta.kubernetes.io/zone are different:

For zoned nodes, the value is <region>-<AZ>, e.g. `centralus-1`.
For unzoned nodes, the value is faultDomain, e.g. `0`.
```

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
  zoned: "true"
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer
```

**Comment by andyzhangx** [comment]
also pls note that don't set zone in pod Affinity if your cluster is not zoned
