### ISSUE TITLE
Windows nodes in AKS sometimes become unable to create or terminate pods

### ISSUE THREAD

**Issue by hallgeirl** [Azure/AKS#1461]
**What happened**:
Now and then (it really seems random) some Windows nodes become unable to create or terminate pods. New pods get stuck in state "ContainerCreating" and pods for deletion get stuck in "Terminating". The node usually report as "Ready". The only solution I've found so far is to reboot the node, or log on to the node and restart the Docker service.

It does seem that existing pods that are already running on the node keeps running fine.

**What you expected to happen**:
I would expect:
1. Nodes that are not able to create or terminate nodes should report NotReady, not Ready.
2. Nodes should not get into this state in the first place of course :)

**How to reproduce it (as minimally and precisely as possible)**:
I don't know what triggers it. We do deploy fairly heavy containers on AKS, huge images with lots of files, and quite a few operations performed on container startup (both file operations and network traffic). Not sure if this is related. It seems to happen with both old nodes and new ones. We've had nodes running for 30+ days without a problem, and we've had some fail after a very short time (hours after creation).

**Anything else we need to know?**:
It might be a coincidence, but sometimes when this happens to ONE node, other nodes also bug out. Currently we have one node reporting "Ready" which is failing, and one reporting "NotReady" (Which obviously is not schedulable, so it's OK). Could be a coincidence.

Here's a bit more info:
kubectl describe of one pod that is stuck in "ContainerCreating" for the node in question:
```> kubectl describe pod -n 932b6071-ea64-4345-817c-a40d2636cc26   app-360-4505-677bc97687-b7q4w
Name:           app-360-4505-677bc97687-b7q4w
Namespace:      932b6071-ea64-4345-817c-a40d2636cc26
Priority:       0
Node:           akswinpol00004y/10.240.0.191
Start Time:     Thu, 20 Feb 2020 14:49:00 +0100
Labels:         app=app-360-4505
                pod-template-hash=677bc97687
Annotations:    prometheus.io/path: /metrics
                prometheus.io/port: 5000
                prometheus.io/scrape: true
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/app-360-4505-677bc97687
Containers:
  app-360:
    Container ID:
    Image:          sicoredevcontainers.azurecr.io/360:5.6.364-pr
    Image ID:
    Port:           81/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:  1
    Requests:
      cpu:      150m
    Readiness:  exec [powershell if(-Not (test-path 'c:\ContainerConfigured.tag')){throw}; curl -Uri http://localhost:81/biz/health -UseBasicParsing;] delay=1s timeout=1s period=30s #success=1 #failure=3
    Environment:
      CONFIG_URL:                 *******
      CONFIG_USER:              *********
      CONFIG_PASSWORD:          ***********
      sicc.instrumentationkey:  ********
      LogLevel:                 Verbose
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-phbr9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-phbr9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-phbr9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=windows
                 kubernetes.io/role=agent
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 os=windows:NoSchedule
Events:
  Type     Reason                  Age                    From                      Message
  ----     ------                  ----                   ----                      -------
  Normal   SandboxChanged          14m (x479 over 17h)    kubelet, akswinpol00004y  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  4m32s (x475 over 17h)  kubelet, akswinpol00004y  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3af069967036963d86cb6d6ee57be4abb55fbd53c630fe75b090f68f46ed3fb9" network for pod "app-360-4505-677bc97687-b7q4w": networkPlugin cni failed to set up pod "app-360-4505-677bc97687-b7q4w_932b6071-ea64-4345-817c-a40d2636cc26" network: unexpected end of JSON input
```

If I log on to the windows node with RDP and check out the event log, I see the same error popping up a LOT in the event log, reported by Docker. Restarting the docker service (which also requires a restart of kubeproxy and kubelet) it stops reporting the error, and the node works again.

Here's kubectl describe of the node that reports ready, but is failing:

```> kubectl describe node akswinpol00004y
Name:               akswinpol00004y
Roles:              agent
Labels:             agentpool=winpol
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2s_v3
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=northeurope
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.azure.com/cluster=MC_DevFarm4274_DevFarm4274_northeurope
                    kubernetes.azure.com/role=agent
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=akswinpol00004y
                    kubernetes.io/os=windows
                    kubernetes.io/role=agent
                    node-role.kubernetes.io/agent=
                    node.kubernetes.io/instance-type=Standard_D2s_v3
                    node.kubernetes.io/windows-build=10.0.17763
                    storageprofile=managed
                    storagetier=Premium_LRS
                    topology.kubernetes.io/region=northeurope
                    topology.kubernetes.io/zone=0
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 18 Feb 2020 03:40:20 +0100
Taints:             os=windows:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  akswinpol00004y
  AcquireTime:     <unset>
  RenewTime:       Fri, 21 Feb 2020 08:27:28 +0100
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 21 Feb 2020 08:23:23 +0100   Tue, 18 Feb 2020 03:40:20 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 21 Feb 2020 08:23:23 +0100   Tue, 18 Feb 2020 03:40:20 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 21 Feb 2020 08:23:23 +0100   Tue, 18 Feb 2020 03:40:20 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 21 Feb 2020 08:23:23 +0100   Tue, 18 Feb 2020 03:40:30 +0100   KubeletReady                 kubelet is posting ready status
Addresses:
  Hostname:    akswinpol00004y
  InternalIP:  10.240.0.191
Capacity:
  attachable-volumes-azure-disk:  4
  cpu:                            2
  ephemeral-storage:              104343548Ki
  memory:                         8388148Ki
  pods:                           30
Allocatable:
  attachable-volumes-azure-disk:  4
  cpu:                            1900m
  ephemeral-storage:              104343548Ki
  memory:                         4403764Ki
  pods:                           30
System Info:
  Machine ID:                           akswinpol00004Y
  System UUID:                          557E42E0-5D1C-46A4-BAA9-F30D1812AA19
  Boot ID:
  Kernel Version:                       10.0.17763.737
  OS Image:                             Windows Server 2019 Datacenter
  Operating System:                     windows
  Architecture:                         amd64
  Container Runtime Version:            docker://19.3.2
  Kubelet Version:                      v1.17.0
  Kube-Proxy Version:                   v1.17.0
ProviderID:                             azure:///subscriptions/50d57ffc-fcc3-48f7-b11f-e637df513e9c/resourceGroups/mc_devfarm4274_devfarm4274_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/akswinpol/virtualMachines/178
Non-terminated Pods:                    (12 in total)
  Namespace                             Name                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                             ----                             ------------  ----------  ---------------  -------------  ---
  02ada02d-54ad-4434-bf61-e779115edac8  app-360-4447-9f5599655-tl86j     150m (7%)     1 (52%)     0 (0%)           0 (0%)         67m
  0964678a-959a-4c12-bcda-c087f41b207e  app-360-4539-55f6b75f95-9snmh    150m (7%)     1 (52%)     0 (0%)           0 (0%)         3d
  216dc6e5-6105-4f82-943a-389543e1a586  app-360-4438-5d86c55b58-mcnxh    150m (7%)     1 (52%)     0 (0%)           0 (0%)         17h
  2f2292f9-7de6-4cca-afc6-9e413ff7df86  app-360-4559-cbbbfd858-z5ckn     150m (7%)     1 (52%)     0 (0%)           0 (0%)         18h
  3b323f10-5a28-4aba-8332-25e6ef915435  app-360-4505-54c866c4c-2hjrg     150m (7%)     1 (52%)     0 (0%)           0 (0%)         2d22h
  8dd06508-c719-4a8d-8e9d-475194bb9424  app-360-4504-c9cbbdcfc-x6wxp     150m (7%)     1 (52%)     0 (0%)           0 (0%)         66m
  9255d779-58ef-40d0-9f3c-502b8d22bb29  app-360-4539-85877c665c-ld5ps    150m (7%)     1 (52%)     0 (0%)           0 (0%)         3d4h
  932b6071-ea64-4345-817c-a40d2636cc26  app-360-4505-677bc97687-b7q4w    150m (7%)     1 (52%)     0 (0%)           0 (0%)         17h
  dc5ffa98-fd3e-4ad4-b591-9362d9d11318  app-360-4555-5d6498b96-5rlhd     150m (7%)     1 (52%)     0 (0%)           0 (0%)         15h
  ebbbb838-61d3-49fe-a930-e8d81cb0367d  app-360-4504-5cf9d67fb9-sbrw4    150m (7%)     1 (52%)     0 (0%)           0 (0%)         66m
  ed2d5e61-f1bc-4174-8bad-383d86facd92  app-360-4504-6c8b5d5976-j24v8    150m (7%)     1 (52%)     0 (0%)           0 (0%)         66m
  eef6d807-76e0-4608-90b3-482655efeea2  app-360-4397-6d5f766c99-qplwt    200m (10%)    660m (34%)  0 (0%)           0 (0%)         2d21h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests     Limits
  --------                       --------     ------
  cpu                            1850m (97%)  11660m (613%)
  memory                         0 (0%)       0 (0%)
  ephemeral-storage              0 (0%)       0 (0%)
  attachable-volumes-azure-disk  0            0
Events:                          <none>
```

Unfortunately the NotReady node were picked off by the autoscaler before I was able to do a kubectl describe on it.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-27T21:11:27Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
Currently 4 nodes on Windows, 2 on Linux

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
IIS web applications

- Others:
I've created a support ticket: 120022122000139

**Comment by hallgeirl** [comment]
I think the part of the issue dealing with containers stuck in "ContainerCreating" is solved through upgrading the Azure CNI component in AKS. We still are struggling a lot with Windows nodes not being able to terminate containers though.  have a new ticket up regarding this: 120041622000069 

The symptoms are similar, but with slightly different errors from what I have in the original issue here. 

kubectl describe pod -n default                                overprovisioning-7696c8887c-ndzln
```
Name:                      overprovisioning-7696c8887c-ndzln
Namespace:                 default
Priority:                  -1
Priority Class Name:       overprovisioning
Node:                      akswinpol00007c/10.240.0.36
Start Time:                Thu, 16 Apr 2020 02:15:55 +0200
Labels:                    pod-template-hash=7696c8887c
                           run=overprovisioning
Annotations:               (none)
Status:                    Terminating (lasts 84m)
Termination Grace Period:  30s
IP:                        10.240.0.51
Controlled By:             ReplicaSet/overprovisioning-7696c8887c
Containers:
  reserve-resources:
    Container ID:   docker://02bee543fb41f344f7a232b31ead084decc73cb8d5560227cb5e325f6f874298
    Image:          mcr.microsoft.com/k8s/core/pause:1.2.0
    Image ID:       docker-pullable://mcr.microsoft.com/k8s/core/pause@sha256:6666771bdc36e6c335f8bfcc1976fc0624c1dd9bc9fa9793ea27ccd6de5e4289
    Port:           (none)
    Host Port:      (none)
    State:          Running
      Started:      Thu, 16 Apr 2020 02:16:10 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        200m
    Environment:  (none)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-w8xwm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-w8xwm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-w8xwm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=windows
                 kubernetes.io/role=agent
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 os=windows:NoSchedule
Events:
  Type     Reason         Age                   From                      Message
  ----     ------         ----                  ----                      -------
  Warning  FailedKillPod  4m52s (x20 over 81m)  kubelet, akswinpol00007c  error killing pod: [failed to 'KillContainer' for 'reserve-resources' with KillContainerError: 'rpc error: code = Unknown desc = operation timeout: context deadline exceeded', failed to 'KillPodSandbox' for 'b2dbf4a0-8394-40fa-a547-c22c4fe4b41a' with KillPodSandboxError: 'rpc error: code
= DeadlineExceeded desc = context deadline exceeded']
  Normal   Killing        4m51s (x21 over 85m)  kubelet, akswinpol00007c  Stopping container reserve-resources
```
- kubectl describe node akswinpol00007c
```
Name:               akswinpol00007c
Roles:              agent
Labels:             agentpool=winpol
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2s_v3
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=northeurope
                    failure-domain.beta.kubernetes.io/zone=4
                    kubernetes.azure.com/cluster=MC_DevFarm4664_DevFarm4664_northeurope
                    kubernetes.azure.com/role=agent
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=akswinpol00007c
                    kubernetes.io/os=windows
                    kubernetes.io/role=agent
                    node-role.kubernetes.io/agent=
                    node.kubernetes.io/instance-type=Standard_D2s_v3
                    node.kubernetes.io/windows-build=10.0.17763
                    storageprofile=managed
                    storagetier=Premium_LRS
                    topology.kubernetes.io/region=northeurope
                    topology.kubernetes.io/zone=4
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 14 Apr 2020 19:44:08 +0200
Taints:             os=windows:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 16 Apr 2020 07:56:44 +0200   Wed, 15 Apr 2020 17:11:18 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 16 Apr 2020 07:56:44 +0200   Wed, 15 Apr 2020 17:11:18 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 16 Apr 2020 07:56:44 +0200   Wed, 15 Apr 2020 17:11:18 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 16 Apr 2020 07:56:44 +0200   Wed, 15 Apr 2020 17:11:18 +0200   KubeletReady                 kubelet is posting ready status
Addresses:
  Hostname:    akswinpol00007c
  InternalIP:  10.240.0.36
Capacity:
 attachable-volumes-azure-disk:  4
 cpu:                            2
 ephemeral-storage:              104343548Ki
 memory:                         8388148Ki
 pods:                           30
Allocatable:
 attachable-volumes-azure-disk:  4
 cpu:                            1900m
 ephemeral-storage:              104343548Ki
 memory:                         4403764Ki
 pods:                           30
System Info:
 Machine ID:                            akswinpol00007C
 System UUID:                           3A73BBC5-6E0D-4887-9791-C148A13CE2D8
 Boot ID:
 Kernel Version:                        10.0.17763.973
 OS Image:                              Windows Server 2019 Datacenter
 Operating System:                      windows
 Architecture:                          amd64
 Container Runtime Version:             docker://19.3.2
 Kubelet Version:                       v1.17.3
 Kube-Proxy Version:                    v1.17.3
ProviderID:                             azure:///subscriptions/50d57ffc-fcc3-48f7-b11f-e637df513e9c/resourceGroups/mc_devfarm4664_devfarm4664_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/akswinpol/virtualMachines/264
Non-terminated Pods:                    (12 in total)
  Namespace                             Name                                 CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                             ----                                 ------------  ----------  ---------------  -------------  ---
  22c89e6b-420f-49b7-bcfb-922e8a832d59  app-360-4928-7b767f6f79-6vzr9        150m (7%)     1 (52%)     0 (0%)           0 (0%)         7h15m
  57b2d22b-13a8-4c92-96af-fb009c4263c5  app-360-4914-5d7d8d45d9-kfskh        150m (7%)     1 (52%)     0 (0%)           0 (0%)         6h16m
  58608a26-dc23-4c13-bb62-6364c650ab45  app-360-4914-5d99c854c9-q7gvq        150m (7%)     1 (52%)     0 (0%)           0 (0%)         21h
  5e6678e7-e37d-4234-8fa1-536762628479  app-360-4861-6696d4b9b5-szdkr        150m (7%)     1 (52%)     0 (0%)           0 (0%)         19h
  609d9beb-64bd-4d14-a269-c98b5871fbe1  app-360-4914-7797779569-6cgbq        150m (7%)     1 (52%)     0 (0%)           0 (0%)         20h
  6521f1f1-ff36-49ad-97bc-e40e7a9c45af  app-360-4681-9ccdb4b47-rbfqt         150m (7%)     1 (52%)     0 (0%)           0 (0%)         6h5m
  696cbce4-3931-48d5-b4d5-1b9c4cb6cf96  app-360-4752-6645ccd9c-k6hbz         150m (7%)     1 (52%)     0 (0%)           0 (0%)         12h
  default                               overprovisioning-7696c8887c-ndzln    200m (10%)    0 (0%)      0 (0%)           0 (0%)         5h50m
  eb4f0986-0232-47e4-ae79-54f0d3afb9da  app-360-4914-5c54d94667-shw9t        150m (7%)     1 (52%)     0 (0%)           0 (0%)         20h
  eb9767ab-4655-4b50-9c0b-e27d942ca70d  app-360-4826-d497b5fc5-w4p8z         150m (7%)     1 (52%)     0 (0%)           0 (0%)         20h
  f44ee306-3e28-471c-9999-d0f3ecccdc78  app-360-4681-6b6f465578-8vt8p        150m (7%)     1 (52%)     0 (0%)           0 (0%)         5h35m
  fbbba94e-3f5d-4c09-a4d9-ec60e24a7f16  app-360-4916-6b7d49c5cd-2cgcf        150m (7%)     1 (52%)     0 (0%)           0 (0%)         19h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests     Limits
  --------                       --------     ------
  cpu                            1850m (97%)  11 (578%)
  memory                         0 (0%)       0 (0%)
  ephemeral-storage              0 (0%)       0 (0%)
  attachable-volumes-azure-disk  0            0
Events:                          (none)


Problem start date and time
Wed, Jan 1, 2020, 12:00 AM GMT+1
```

**Comment by MikkelHegn** [comment]
Looking at the support case, it seems the nodes ran out of resources. This issue describes how Kubernetes on Windows deals with resource reservations and limits: https://github.com/kubernetes/kubernetes/issues/73417#issuecomment-465806482

**Comment by hallgeirl** [comment]
Yeah, that's what I got the impression of as well. What I'm struggling with though is that a pod can take down the whole node by being a bit greedy on memory. I would have expected the memory reservations for the kubelet to take care of that. It is a real issue for us that the system services (kubelet, etc.) get completely messed up like this... If the reservations made by the kubelet is not actually reserved - what is then the point of that reservation?

About setting limits == requests... there's one challenge here as well - and that is spikes in memory usage. If one pod spikes, that SHOULD be OK, and is not a problem when running in a non-kubernetes environment. However, having to set strict limits to not overshoot memory usage kind of rules that possibility out, so we end up with underutilized nodes, because we have to account for those spikes in memory usage. And what about paging? I do agree that overspending memory is not a good idea - since paging obviously will slow the application down. But slowing down temporarily is arguably better than having to restart the whole node because system services crash.

Of course, any advise on this is welcome. The support case is still open. Not sure what the outcome will be...

Thank you anyway for pointing me to that other github issue on memory handling in Windows. This is an interesting read.

**Comment by MikkelHegn** [comment]
The _reservations_ (kube-reserved and system-reserved) will deduct form the _allocatable_ resources on the node, which are evaluated at scheduling time based on the _requests_ described in the pod spec.

Only pod _limits_ are runtime enforced. For Windows this translates to a [JOB_OBJECT_LIMIT_JOB_MEMORY (virtual memory limit)](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_extended_limit_information). Since Windows doesn't kill processes, it's up to the application to handle out of memory exceptions, but that's orthogonal to running a Windows process in a container or _natively_.

There's currently no good way to ensure reservation for certain processes vs. others, using Windows and Kubernetes. This can turn in to a longer debate about how this should work with Kubernetes - the Windows vs. Linux way or the Kubernetes way :-). Using the missing kubelet implementations on Windows could be one way to go.

> --eviction-hard and --eviction-soft are not implemented
> MemoryPressure Condition is not implemented in Window

That would put the responsibility on the kubelet to evict containers at certain thresholds, but would still not enforce reservations of resources for other processes. This is definitely a conversation for Kubernetes Upstream @craiglpeters @marosset @immuzz - FYI

For now you'll have to rely on monitoring memory consumption to find the right scale units and node to pod ration for you work loads, and use requests to enforce those ratios.

**Comment by hallgeirl** [comment]
Thanks a lot @MikkelHegn. This is very useful information. We have a few things to look into moving forward. 

I am still concerned about the kubernetes services simply crashing on the node though. Shouldn't the pagefile be used here instead of the processes just crashing due to OOM? That's usually the normal behavior in Windows. This would obviously cause slowdown, but not a complete crash of the node.

Any comments around this?

**Comment by MikkelHegn** [comment]
From what I read in the above support case, the Azure CNI plug-in got an "out-of-memory" exception, preventing the pods from terminating or creating. From my understanding that means Windows ran out of virtual memory to allocate, but I'm starting to get beyond my comfort zone at this point :-)

**Comment by hallgeirl** [comment]
I understand. :-)

But - shouldn't the node be set as Unhealthy if CNI crashes? Since that plugin must run for the node to function, if the plugin crashes, I would expect the node to be set in unhealthy state.

**Comment by MikkelHegn** [comment]
Regarding the CNI crash, I'm think it restarts, bringing the node back to a working state - do you see otherwise?

`kubectl top` does not take allocatable in to account, it reports the actual usage as reported by the kubelet summary API: https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#measuring-resource-usage. As the kubelet on Windows doesn't implement hard-eviction and memory pressure, there's a missing link in the e2e resource management on Windows, which means overcommitting. like you're doing in this scenario, will likely cause resource starvation.

**Comment by hallgeirl** [comment]
> 
> 
> Regarding the CNI crash, I'm think it restarts, bringing the node back to a working state - do you see otherwise?
> 
> `kubectl top` does not take allocatable in to account, it reports the actual usage as reported by the kubelet summary API: https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#measuring-resource-usage. As the kubelet on Windows doesn't implement hard-eviction and memory pressure, there's a missing link in the e2e resource management on Windows, which means overcommitting. like you're doing in this scenario, will likely cause resource starvation.

Thanks for the clarification on kubectl top.

When the node comes into this state, it's not being fixed before I go into the Azure portal and restart the node itself. So it doesn't seem to fix itself by restarting...

**Comment by MikkelHegn** [comment]
Got it, do you know if the node goes in to an unhealthy state?

**Comment by hallgeirl** [comment]
The node reports "Ready" on those nodes where this happens most of the time. We do see "NotReady" nodes from time to time, but these nodes that get stuck usually are just sitting there reporting Ready, even though pods are not able to terminate, or sometimes the readiness probes are not able to run. Until we reboot the node...

**Comment by MikkelHegn** [comment]
Thx - we only remediate notes which are `unhealthy` for a certain period of time: https://docs.microsoft.com/en-us/azure/aks/node-auto-repair#how-aks-checks-for-unhealthy-nodes

I'll follow-up to make sure we capture this condition.

**Comment by hallgeirl** [comment]
Thanks @MikkelHegn! :-) Looking forward to that change!

**Comment by sussexrick** [comment]
@MikkelHegn The last page you linked to says node auto-repair is not implemented for Windows Server node pools. Is there a plan/timescale for implementation?

**Comment by MikkelHegn** [comment]
@keikhara - see bove regarding auto-repair.

**Comment by keikhara** [comment]
@sussexrick we have implemented auto-repair on windows now.

**Comment by hallgeirl** [comment]
> 
> 
> @sussexrick we have implemented auto-repair on windows now.

@keikhara Is this available for all new AKS windows nodes from now on? What version of Kubernetes do we need to select for our AKS node pool to get auto-repair? Anything else we need to do?

**Comment by anurag-arya** [comment]
We suspected to have the same issue and we've also upgraded one of our clusters with kubernetes version 1.17.9 and still see several cni failure logs on windows nodes kubelet logs. Only rebooting resolves this issue temporarily. 
`failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod `

**Comment by heoelri** [comment]
> > @sussexrick we have implemented auto-repair on windows now.
> 
> @keikhara Is this available for all new AKS windows nodes from now on? What version of Kubernetes do we need to select for our AKS node pool to get auto-repair? Anything else we need to do?

"Auto node-repair should be for all k8s version. You do not need to do anything. This is the same for Linux." @keikhara
