### ISSUE TITLE
Crash loops in azurefile-csi and azuredisk-csi (Error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified)

### ISSUE THREAD

**Issue by adoprog** [Azure/AKS#2568]
**What happened**:

After the release https://github.com/Azure/AKS/releases/tag/2021-09-16 has rolled out to the region (East US) where our AKS cluster is deployed, windows nodes fail to run **azurefile-csi** and **azuredisk-csi**, both enter the crash loop with a similar exception: "Error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified."

![azure_error](https://user-images.githubusercontent.com/1315023/135031971-cc187e02-675c-4aa5-acbc-b886f08aa0cd.PNG)

**How to reproduce it (as minimally and precisely as possible)**:

Have a cluster in one of the affected regions and force autoscaler to create a new Windows node.

**Anything else we need to know?**:

**Environment**: 1.21.2 (previously upgraded from 1.1x, not brand new 1.21.2)
- Kubernetes version (use `kubectl version`): 1.21.2
- Size of cluster (how many worker nodes are in the cluster?): 5+
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Windows containers that use PVs.
- Others:

**Comment by andyzhangx** [comment]
@adoprog can you `Upgrade` vmss model in the vmss page in azure portal? Create a new windows node pool could also mitigate this issue. Thanks.

**Comment by adoprog** [comment]
Yep, tried that - did not help. With the help of support engineer we've found out that many clusters are missing property called "enableCSIProxy" in a cluster definition. I suppose, the clusters that were upgraded from 1.18 and earlier are the ones that don't have it.

Unfortunately, this property is not exposed in UI or Azure CLI so we can't "enable" it on problematic clusters.

**Comment by andyzhangx** [comment]
Does creating a new windows node pool work?  @adoprog

**Comment by adoprog** [comment]
Rechecking it now, will report back in 10 mins

**Comment by adoprog** [comment]
Creating new node pool does not help. The property is not there and the services crash just like in old pool.

**Comment by ZeroMagic** [comment]
@adoprog  Which region is your cluster in?

**Comment by adoprog** [comment]
East US

**Comment by adoprog** [comment]
Australia East - same issues

**Comment by andyzhangx** [comment]
pls file an azure ticket, we already fixed one cluster in eastus region. The upgrade fix has already being rolled out, with one more day, it would be rolled out to all regions, while for those windows clusters that were upgraded to v1.21 without the upgrade fix, we need to manually workaround this issue.

**Comment by cailyoung** [comment]
We've opened ticket `2109280060001140` for Australia East.

**Comment by adoprog** [comment]
After the fix, both services run better but still crash randomly (East US cluster is usable, Australia East one - not really). We also have the ticket open and informed support team.

**Comment by andyzhangx** [comment]
the windows node should have at least 4 cores CPU vm size, otherwise the driver pod would crash

**Comment by adoprog** [comment]
We tried D8S_v3 and D16S_v3 for Windows nodes, it fails on both. 
csi-node-driver-registrar:v2.3.0 exits with no exception in a log

**Comment by andyzhangx** [comment]
> We tried D8S_v3 and D16S_v3 for Windows nodes, it fails on both. csi-node-driver-registrar:v2.3.0 exits with no exception in a log

@adoprog could you provide `kubectl describe po csi-azuredisk-node-win-xxx -n kube-system` output if it failed?

**Comment by adoprog** [comment]
[describe.txt](https://github.com/Azure/AKS/files/7250522/describe.txt)

Sure, I've attached the output.

**Comment by adoprog** [comment]
The errors on the pods are similar to the one below. Not sure if attaching crashes driver or driver crash causes this error. 

MountVolume.MountDevice failed for volume "pvc-e91eaa3c-82cc-4ebb-bba6-95613aa556dd" : rpc error: code = Internal desc = could not format "22"(lun: "2"), and mount it at "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-e91eaa3c-82cc-4ebb-bba6-95613aa556dd\\globalmount"

**Comment by andyzhangx** [comment]
@adoprog could you run:
 - `kubectl edit ds csi-azuredisk-node-win -n kube-system`
 - `kubectl edit ds csi-azurefile-node-win -n kube-system`

change `timeoutSeconds: 15` for `csi-node-driver-registrar` inside container livenessProbe, that would workaround the issue, thanks.
```yaml
        image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.3.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - cmd
              - /c
              - del /f C:\registration\disk.csi.azure.com-reg.sock C:\csi\disk.csi.azure.com\csi.sock
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar.exe
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --mode=kubelet-registration-probe
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
```

**Comment by andyzhangx** [comment]
> The services are not crashing after the workaround, but the volumes (at least existing ones, haven't tested new ones yet) are not attaching and show error:
> 
> MountVolume.MountDevice failed for volume "pvc-8646cb0b-78cf-4383-86df-1b969523bd74" : rpc error: code = Internal desc = could not format "13"(lun: "0"), and mount it at "\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-8646cb0b-78cf-4383-86df-1b969523bd74\globalmount"

@adoprog pls try delete the pod, that would trigger attach & mount process again, thanks.

**Comment by adoprog** [comment]
Tried that, did not help, same error occurs.

**Comment by andyzhangx** [comment]
> Tried that, did not help, same error occurs.

@adoprog does new pod works? You may cordon that node, delete pod, make it reschedule to other node, if mount still not works, try provide node driver logs by https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by adoprog** [comment]
New service (i.e. new pod, new PV) worked. Log file attached.
[csi-azuredisk-node.log](https://github.com/Azure/AKS/files/7251770/csi-azuredisk-node.log)

**Comment by andyzhangx** [comment]
> New service (i.e. new pod, new PV) worked. Log file attached. [csi-azuredisk-node.log](https://github.com/Azure/AKS/files/7251770/csi-azuredisk-node.log)

@adoprog I think it's related to abnormal state of driver a few moments ago, try cordon the node, delete pod in problem, and pod would be scheduled to the new node, so it's like new pod, thanks.

**Comment by adoprog** [comment]
Cordoned node, killed the pod, still the same error when attaching:

Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-vrtsm data]: timed out waiting for the condition         Warning  FailedMount             47s (x8 over 3m12s)  kubelet, akswincsi000003  MountVolume.MountDevice failed for volume "pvc-8646cb0b-78cf-4383-86df-1b969523bd74" : rpc error: code = Internal desc = could not format "18"(lun: "0" ), and mount it at "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-8646cb0b-78cf-4383-86df-1b969523bd74\\globalmount"

**Comment by adoprog** [comment]
Error sequence in pod (maybe this helps):

1) AttachVolume.Attach succeeded for volume "pvc-8646cb0b-78cf-4383-86df-1b969523bd74" 

2) Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-7p2bb data]: timed out waiting for the condition 

3) MountVolume.MountDevice failed for volume "pvc-8646cb0b-78cf-4383-86df-1b969523bd74" : rpc error: code = Internal desc = could not format "31"(lun: "0"),  and mount it at "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-8646cb0b-78cf-4383-86df-1b969523bd74\\globalmount"

**Comment by andyzhangx** [comment]
> Error sequence in pod (maybe this helps):
> 
> 1. AttachVolume.Attach succeeded for volume "pvc-8646cb0b-78cf-4383-86df-1b969523bd74"
> 2. Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-7p2bb data]: timed out waiting for the condition
> 3. MountVolume.MountDevice failed for volume "pvc-8646cb0b-78cf-4383-86df-1b969523bd74" : rpc error: code = Internal desc = could not format "31"(lun: "0"),  and mount it at "\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-8646cb0b-78cf-4383-86df-1b969523bd74\globalmount"

@adoprog can you run `k exec -it csi-azuredisk-node-win-hntvv -n kube-system -c azuredisk cmd` and then `type c:\k\csi-proxy.err.log` & `type c:\k\csi-proxy.log` to get csi-proxy logs on that node?

And have you used those PVCs on Linux node?

**Comment by adoprog** [comment]
type c:\k\csi-proxy.err.log:
![csi-proxy err log](https://user-images.githubusercontent.com/1315023/135276018-5f1b8334-bc45-4f44-88b2-4b1c10235737.png)

type c:\k\csi-proxy.log:
nothing

**Comment by adoprog** [comment]
What I also noticed, that old and new PVs have different tags format in Azure:

Old:
![tags_old](https://user-images.githubusercontent.com/1315023/135276295-5b7f4644-b245-4156-a84e-89d0f0a15514.PNG)

New:
![tags_new](https://user-images.githubusercontent.com/1315023/135276312-343b8444-6873-4def-8253-9ccef57cdc79.PNG)

**Comment by andyzhangx** [comment]
tag format are changed from azure disk csi driver v1.7.0: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1009
And about disk format error, it seems those disks are broken, could you create new disks?

**Comment by adoprog** [comment]
Not really, we have hundreds of such instances each comes with disks, often with important data.

**Comment by andyzhangx** [comment]
> I tried to attach on of the disks to a VM in the same subscription and it worked, showed the data...

@adoprog can you run Powershell command `Get-Partition` inside that Windows VM and paste the output? thanks.

**Comment by adoprog** [comment]
![disk](https://user-images.githubusercontent.com/1315023/135285325-64aa3074-1fec-44cc-9885-272f050f0da9.PNG)

**Comment by andyzhangx** [comment]
@adoprog thanks. I found this is a breaking change brought from upstream project: csi-proxy, already worked out a PR: https://github.com/kubernetes-csi/csi-proxy/pull/175, about how to mitigate this issue soon on AKS, I think we need to switch back to csi-proxy beta interface on AKS first.

**Comment by andyzhangx** [comment]
@adoprog how can I format a disk with `IFS` type? How was that disk created, by azure disk driver, if so, what's the k8s version? I would like to repro this issue, thanks.

**Comment by zhiweiv** [comment]
There is no workaround and we have to wait right? Some of csi pods began to crash without any actions.
```
I0930 02:02:19.890199   11536 safe_mounter_windows.go:279] failed to connect to csi-proxy v1 with error: open \\.\\pipe\\csi-proxy-filesystem-v1: The system cannot find the file specified., will try with v1Beta
E0930 02:02:19.890199   11536 safe_mounter_windows.go:289] failed to connect to csi-proxy v1beta with error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.
F0930 02:02:19.890199   11536 azurefile.go:243] Failed to get safe mounter. Error: open \\.\\pipe\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.
```
```
C:\Users\zwliu>kubectl -n kube-system -o wide get pods | findstr csi-azurefile-node-win
csi-azurefile-node-win-4jmmp          3/3     Running            0          9d      10.5.4.194   akswin100000b                    <none>           <none>
csi-azurefile-node-win-6xg4p          1/3     CrashLoopBackOff   11         5m48s   10.5.2.171   akswinjob000000                  <none>           <none>
csi-azurefile-node-win-7bwmx          3/3     Running            0          9d      10.5.5.52    akswin1000005                    <none>           <none>
csi-azurefile-node-win-85fht          3/3     Running            0          9d      10.5.4.176   akswin100000a                    <none>           <none>
csi-azurefile-node-win-86k7h          1/3     CrashLoopBackOff   319        9h      10.5.5.144   akswin1000008                    <none>           <none>
csi-azurefile-node-win-bpcjh          3/3     Running            0          9d      10.5.5.121   akswin1000007                    <none>           <none>
csi-azurefile-node-win-jkvd8          3/3     Running            0          9d      10.5.5.88    akswin1000006                    <none>           <none>
csi-azurefile-node-win-k49hx          2/3     CrashLoopBackOff   317        9h      10.5.5.173   akswin1000009                    <none>           <none>
csi-azurefile-node-win-khcd9          3/3     Running            3          46h     10.5.1.136   akswinjob000002                  <none>           <none>
csi-azurefile-node-win-l8zwl          3/3     Running            0          8d      10.5.0.21    akswin100000c                    <none>           <none>
csi-azurefile-node-win-mcbj7          3/3     Running            0          9d      10.5.5.19    akswin1000004                    <none>           <none>
csi-azurefile-node-win-mslqf          3/3     Running            0          9d      10.5.4.214   akswin1000002                    <none>           <none>
csi-azurefile-node-win-t42hx          3/3     Running            0          9d      10.5.4.255   akswin1000003                    <none>           <none>
csi-azurefile-node-win-vpf9h          3/3     Running            0          9d      10.5.4.122   akswin1000001                    <none>           <none>
csi-azurefile-node-win-wlksg          3/3     Running            0          9d      10.5.4.46    akswin1000000                    <none>           <none>
```

**Comment by andyzhangx** [comment]
@zhiweiv 
try this workaround: https://github.com/Azure/AKS/issues/2568#issuecomment-930098854

**Comment by zhiweiv** [comment]
Not work for me, we are using E2_V4 for Windows nodes.
[csi-azurefile-node-win-llrml.zip](https://github.com/Azure/AKS/files/7256293/csi-azurefile-node-win-llrml.zip)
```
C:\Users\zwliu>kubectl -n kube-system get pods | findstr csi-azurefile-node-win
csi-azurefile-node-win-4jmmp          3/3     Running            0          9d
csi-azurefile-node-win-7bwmx          3/3     Running            0          9d
csi-azurefile-node-win-85fht          3/3     Running            0          9d
csi-azurefile-node-win-9ptd5          2/3     CrashLoopBackOff   13         8m54s
csi-azurefile-node-win-bg4t5          1/3     CrashLoopBackOff   15         8m49s
csi-azurefile-node-win-bpcjh          3/3     Running            0          9d
csi-azurefile-node-win-bz9fq          1/3     CrashLoopBackOff   11         5m5s
csi-azurefile-node-win-jkvd8          3/3     Running            0          9d
csi-azurefile-node-win-khcd9          3/3     Running            3          46h
csi-azurefile-node-win-l8zwl          3/3     Running            0          8d
csi-azurefile-node-win-llrml          1/3     CrashLoopBackOff   13         8m56s
csi-azurefile-node-win-mcbj7          3/3     Running            0          9d
csi-azurefile-node-win-mslqf          3/3     Running            0          9d
csi-azurefile-node-win-t42hx          3/3     Running            0          9d
csi-azurefile-node-win-vpf9h          3/3     Running            0          9d


```

**Comment by andyzhangx** [comment]
@zhiweiv the kubelet response on your E2_V4 node may be too slow, can you try E4_V4 node?

**Comment by zhiweiv** [comment]
Hmm, will the 4 cores be the least requirement for csi afterward? or just a temporary mitigation?

**Comment by andyzhangx** [comment]
> Hmm, will the 4 cores be the least requirement for csi afterward? or just a temporary mitigation?

@zhiweiv If you want to run as production, I think 4 cores should be the at least. Try 4 cores first, the automatic fix is already on the way.

**Comment by zhiweiv** [comment]
Our production clusters are using 4 cores, for testing clusters we prefer 2 cores to save cost. I will try 4 cores first.

**Comment by adoprog** [comment]
@andyzhangx All the volumes have been created with K8S, same 1.21.2 version as before. The only difference I believe is that they were created before the release 2021-09-16 was applied and new node pool created.

**Comment by zhiweiv** [comment]
@andyzhangx 
```
Still crash on newly created 4 cores VMs.
C:\Users\zwliu>kubectl -n kube-system get pods -o wide | findstr csi | findstr akswin2
csi-azuredisk-node-win-2g9hl          1/3     CrashLoopBackOff   26         36m     10.5.2.131   akswin2000000  
csi-azuredisk-node-win-n5j99          1/3     CrashLoopBackOff   26         37m     10.5.2.152   akswin2000001  
csi-azurefile-node-win-l7cx4          1/3     CrashLoopBackOff   27         37m     10.5.3.8     akswin2000001  
csi-azurefile-node-win-z9dh9          1/3     CrashLoopBackOff   27         36m     10.5.1.165   akswin2000000  
```

**Comment by adoprog** [comment]
@andyzhangx Not sure when and why partitioning has changed, but previously it was definitely possible to attach a K8S windows volume to a VM and browse the files. This is not the case with the "new" volumes.

**Comment by andyzhangx** [comment]
> e volumes

@adoprog the volumes in problem were created before k8s 1.21 version, right?

**Comment by adoprog** [comment]
In some cases the volumes were created in k8s 1.21.

I tried it on test 1.21 cluster yesterday:
1) Created an instance with volume
2) Stopped the pods
3) Created new node pool (old node pool was also 1.21 but probably older image version)
4) Started the pods 
5) An error occurs, the instance can't start due to volume attachment failure

**Comment by andyzhangx** [comment]
> @andyzhangx Still crash on newly created 4 cores VMs.
> 
> ```
> C:\Users\zwliu>kubectl -n kube-system get pods -o wide | findstr csi | findstr akswin2
> csi-azuredisk-node-win-2g9hl          1/3     CrashLoopBackOff   26         36m     10.5.2.131   akswin2000000  
> csi-azuredisk-node-win-n5j99          1/3     CrashLoopBackOff   26         37m     10.5.2.152   akswin2000001  
> csi-azurefile-node-win-l7cx4          1/3     CrashLoopBackOff   27         37m     10.5.3.8     akswin2000001  
> csi-azurefile-node-win-z9dh9          1/3     CrashLoopBackOff   27         36m     10.5.1.165   akswin2000000  
> ```
> 
> ```
> C:\Users\zwliu>kubectl describe node akswin2000000
> Name:               akswin2000000
> CreationTimestamp:  Thu, 30 Sep 2021 13:40:46 +0800
> Capacity:
>   cpu:                4
>   ephemeral-storage:  261629948Ki
>   memory:             33553972Ki
>   pods:               50
> ```

@zhiweiv sorry, my fault, your issue is another one, pls file an azure ticket, ask our support to add `"enableCSIProxy": true` into managed cluster properties since there was an upgrade scenario we missed(already fixed on current release)
```yaml
        "windowsProfile": {
            "adminUsername": "azureuser",
            "enableCSIProxy": true
        },
```

**Comment by andyzhangx** [comment]
> In some cases the volumes were created in k8s 1.21.
> 
> I tried it on test 1.21 cluster yesterday:
> 
> 1. Created an instance with volume
> 2. Stopped the pods
> 3. Created new node pool (old node pool was also 1.21 but probably older image version)
> 4. Started the pods
> 5. An error occurs, the instance can't start due to volume attachment failure

@adoprog sorry for the delay, finally we figured out that the disk attach failure was caused by last mitigation, we mistakenly used csi-proxy v1.0.0 binary for your clusters(while all other aks clusters are using v0.2.2 which does not have the compatibility issue), we will correct the csi-proxy config for all your clusters, and then our support will ask you to do vmss upgrade. After vmss upgrade, it should work.

And thanks for the patience, we found csi-proxy v1.0.0 has severe disk type compatibility issue, so AKS will abandon this csi-proxy v1.0.0, and upgrade to csi-proxy v1.1.0 release directly.

**Comment by andyzhangx** [comment]
close this issue since the liveness timeout fix has been rolled out to all regions.
