### ISSUE TITLE
[BUG] Please do not upgrade to k8s 1.25 if you are using calico

### ISSUE THREAD

**Issue by AbelHu** [Azure/AKS#3394]
**Describe the bug**
Calico does not work in k8s 1.25. We are working on it. Please do not upgrade to k8s 1.25 if you are using calico before this issue is closed.

**Comment by rouke-broersma** [comment]
Can't you just detect this and block the upgrade for this scenario? An issue on github hardly seems like the best way to distribute this warning 🤨

**Comment by AbelHu** [comment]
FYI: @rouke-broersma we have sent a notification to all AKS Windows calico customers.

**Comment by siegenthalerroger** [comment]
This isn't just windows specific: https://github.com/Azure/AKS/issues/3403

**Comment by higordearaujo-bsy** [comment]
[This comment](https://github.com/Azure/AKS/issues/3403#issuecomment-1362851541) says that it's a matter of upgrading to a newer tigera operator. I know it'll have to be tested first, but can we expect this to be solved by the 2023-01-15 release?

**Comment by A-Lynch** [comment]
Is there an update available for this bug?

**Comment by AbelHu** [comment]
> Is there an update available for this bug?

We are rolling out the hotfix and it is expected to be available in all impacted regions by end of this week.

**Comment by bsmithyman** [comment]
Fantastic, thanks @AbelHu

**Comment by AbelHu** [comment]
The fix is available in all impacted regions now. Please upgrade your impacted cluster (v1.25.2) to v1.25.4 to get the fix. If you cluster is using v1.25.4, you may need to create a new cluster or file a support ticket to involve AKS engineers to help you.
NOTE: If you are using 1.25 preview, please do the upgrade after 1.25 is GA in your region.

**Comment by matthew-fawcett** [comment]
Anyone else had a problem upgrading their 1.25.2 clusters to 1.25.4 to resolve this bug?  We have one in the North Europe which entered a failed state while upgrading

**Comment by rgarcia89** [comment]
> > Is there an update available for this bug?
> 
> We are rolling out the hotfix and it is expected to be available in all impacted regions by end of this week.

Can you please explain what changes has been done to fix the issue?

**Comment by logamanig** [comment]
Hi, is it resolved in 1.25.4? Failed to upgrade from 1.24.6 to 1.25.4 and no luck creating new cluster as well. Finally I end up recreating v1.24.6 as my original cluster was in failed state.

My setup includes,
Private cluster
Kubenet cni 
Calico network policy
Ephemeral os disk

**Comment by AbelHu** [comment]
The bug mentioned in this GitHub issue has been fixed. Please free to file a support ticket issue to get the help if you hit any other issues.

**Comment by logamanig** [comment]
I tried to upgrade and it fails. Is this ticket about only to the linked ticket? When still not able to upgrade the cluster from 1.24.6

**Comment by bgrainger** [comment]
> Failed to upgrade from 1.24.6 to 1.25.4 and no luck creating new cluster as well. Finally I end up recreating v1.24.6 as my original cluster was in failed state.

Same story here (with a similar cluster setup).

Created Azure Support Ticket 2301130010003573 to track it, but ended up recreating the cluster before a resolution was found (as we had workloads we needed to run).

**Comment by AbelHu** [comment]
> 2301130010003573

cc @paulgmiller @mattstam @wedaly

**Comment by robbiezhang** [comment]
Reopen the case, since we find another issue with calico on 1.25.

**Comment by matthew-fawcett** [comment]
Any updates on this issue?

**Comment by dennis-menge** [comment]
The issue is fixed across all public regions (China excluded).

**Comment by BenjaminHerbert** [comment]
@dennis-menge That's good news. One question remains for me:

[Release notes for Release 2023-01-08](https://github.com/Azure/AKS/releases/tag/2023-01-08) state:
> A bug regarding Kubernetes version 1.25 and the tigera operator has been https://github.com/Azure/AKS/issues/3394. If your cluster is already running on v1.25.4, please create a new cluster or file a support ticket with AKS for any further help.

How can I check if a cluster is affected? Having to create a new cluster because of an automatically applied upgrade would be kind of ... _unfortunate_.

**Comment by logamanig** [comment]
I tried to create a cluster but it also failed

**Comment by dennis-menge** [comment]
> @dennis-menge That's good news. One question remains for me:
> 
> [Release notes for Release 2023-01-08](https://github.com/Azure/AKS/releases/tag/2023-01-08) state:
> 
> > A bug regarding Kubernetes version 1.25 and the tigera operator has been #3394. If your cluster is already running on v1.25.4, please create a new cluster or file a support ticket with AKS for any further help.
> 
> How can I check if a cluster is affected? Having to create a new cluster because of an automatically applied upgrade would be kind of ... _unfortunate_.

I think you could check one of the `tigera-operator` pods in the `tigera-operator` namespace, like:

```
Containers:
  calico-node:
    Container ID:   containerd://6b6fbe144e4aee9aacb54fe7c3f5d2b03b84afe5d754a7ce1989b76dfdb7984d
    Image:          mcr.microsoft.com/oss/calico/node:v3.24.0
```

If it shows 3.24.0, everything should be fine.

**Comment by dennis-menge** [comment]
> @dennis-menge That's good news. One question remains for me:
> 
> [Release notes for Release 2023-01-08](https://github.com/Azure/AKS/releases/tag/2023-01-08) state:
> 
> > A bug regarding Kubernetes version 1.25 and the tigera operator has been #3394. If your cluster is already running on v1.25.4, please create a new cluster or file a support ticket with AKS for any further help.
> 
> How can I check if a cluster is affected? Having to create a new cluster because of an automatically applied upgrade would be kind of ... _unfortunate_.

As far as I know the comment in the release notes was referring to the initial problem reported here. The 2nd issue mentioned by @robbiezhang is not related to that.

**Comment by aresabalo** [comment]
I have been upgrading my AKS clusters in azure for 2 years without problems. Actually my cluster aks is 1.24.6 but reading the problems that are happening with v1.25 I'm really worried...

Problems with Calico, PDBs, etc. and the solution that is being provided in some cases is to recreate the cluster!!!!. This may not be the solution for a production cluster with many workload. 

There should at least be a way to revert to the previous version of the cluster from a backup of the control nodes.

**Comment by darose** [comment]
> The issue is fixed across all public regions (China excluded).

@dennis-menge Is it now safe to upgrade clusters to 1.25?  This bug is still open.  Should we be waiting until it is closed before upgrading?

**Comment by mmdiez** [comment]
> > The issue is fixed across all public regions (China excluded).
> 
> @dennis-menge Is it now safe to upgrade clusters to 1.25? This bug is still open. Should we be waiting until it is closed before upgrading?

We had a cluster in failed state because of this problem, I tried again to upgrade and is still failing, so i dont think that is fixed

**Comment by nnellanspdl** [comment]
> I have been upgrading my AKS clusters in azure for 2 years without problems. Actually my cluster aks is 1.24.6 but reading the problems that are happening with v1.25 I'm really worried...
> 
> Problems with Calico, PDBs, etc. and the solution that is being provided in some cases is to recreate the cluster!!!!. This may not be the solution for a production cluster with many workload.
> 
> There should at least be a way to revert to the previous version of the cluster from a backup of the control nodes.

I'm in the same boat, have been updating my clusters for a long time now.

One cluster we recently updated to 1.24.6.  The tigera-operator Pod on this cluster is running image:  mcr.microsoft.com/oss/tigera/operator:v1.23.8

Will this be upgraded automatically to a new tigera-operator version when we upgrade the cluster to 1.25.x ?

**Comment by dennis-menge** [comment]
> One cluster we recently updated to 1.24.6. The tigera-operator Pod on this cluster is running image: mcr.microsoft.com/oss/tigera/operator:v1.23.8
> 
> Will this be upgraded automatically to a new tigera-operator version when we upgrade the cluster to 1.25.x ?


yes, you should see the following (v3.24.0) on 1.25:
```
Containers:
  calico-node:
    Container ID:   containerd://6b6fbe144e4aee9aacb54fe7c3f5d2b03b84afe5d754a7ce1989b76dfdb7984d
    Image:          mcr.microsoft.com/oss/calico/node:v3.24.0
    Image ID:       mcr.microsoft.com/oss/calico/node@sha256:29f9ce25204d7b5a84addf9e38a93c24d102baca40fa0eec173fce95b6af7e46
```

**Comment by paulgmiller** [comment]
We believe we mitigated the issue with 1.25 in all public regions on 1/22 at 5PM PST. Mooncake is behind because of lockdown for lunar festival. 

If you're still seeing issues please file a support ticket so that we can get your cluster details. Mention this issue and ask them refernce icm 361120059 to esclate if its still a calico issue.

**Comment by robbiezhang** [comment]
As of 19:00 1/23/2023 UTC, the fix has been deployed to all the regions in Azure Public Cloud and US Gov Cloud (Fairfax). The release to China Cloud (Mooncake) will be delivered after the Lunar New Year holiday ends in China.

**Comment by nnellanspdl** [comment]
> yes, you should see the following (v3.24.0) on 1.25:
> 
> ```
> Containers:
>   calico-node:
>     Container ID:   containerd://6b6fbe144e4aee9aacb54fe7c3f5d2b03b84afe5d754a7ce1989b76dfdb7984d
>     Image:          mcr.microsoft.com/oss/calico/node:v3.24.0
>     Image ID:       mcr.microsoft.com/oss/calico/node@sha256:29f9ce25204d7b5a84addf9e38a93c24d102baca40fa0eec173fce95b6af7e46
> ```

I think we're getting confused here.  I have a namespace called `tigera-operator`.  Inside I have one pod named `tigera-operator-xxx`.  This Pod is using container image:  `mcr.microsoft.com/oss/tigera/operator:v1.23.8`.  What will this be updated to when I upgrade the cluster to 1.25.x ?

Your answer is for the `calico-node-xxxx` Pods under the `calico-system` Namespace.

**Comment by dennis-menge** [comment]
> > yes, you should see the following (v3.24.0) on 1.25:
> > ```
> > Containers:
> >   calico-node:
> >     Container ID:   containerd://6b6fbe144e4aee9aacb54fe7c3f5d2b03b84afe5d754a7ce1989b76dfdb7984d
> >     Image:          mcr.microsoft.com/oss/calico/node:v3.24.0
> >     Image ID:       mcr.microsoft.com/oss/calico/node@sha256:29f9ce25204d7b5a84addf9e38a93c24d102baca40fa0eec173fce95b6af7e46
> > ```
> 
> I think we're getting confused here. I have a namespace called `tigera-operator`. Inside I have one pod named `tigera-operator-xxx`. This Pod is using container image: `mcr.microsoft.com/oss/tigera/operator:v1.23.8`. What will this be updated to when I upgrade the cluster to 1.25.x ?
> 
> I think your answer is referring to the `calico-node-xxxx` Pods under the `calico-system` Namespace.

Tigera-Operator is bumped to 1.28 in AKS 1.25, which deploys calico 3.24.0: see https://github.com/tigera/operator/releases/tag/v1.28.0
