### ISSUE TITLE
[BUG] Windows node reports less CPU usage than its pods

### ISSUE THREAD

**Issue by den4md** [Azure/AKS#4028]
**Describe the bug**
`kubectl top node` command is showing less cpu load for windows nodes than expected.

**To Reproduce**
1. Create a nodepool with 1 Windows2022/2019 node running k8s 1.27.7 version (in my example: A2_v2, D8_v5 or B2ms)
2. Create simple cpu-consuming deployment. For example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-cpu-load
  name: win-cpu-load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: win-cpu-load
  template:
    metadata:
      labels:
        app: win-cpu-load
      name: win-cpu-load
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.azure.com/agentpool
                      operator: In
                      values:
                        - test00
      containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/servercore:ltsc2022
        command:
        - powershell.exe
        - -command
        - "while ($true) { $result = 1; foreach ($number in 1..100000000) {$result = $result * $number}; Write-Host $result; Start-Sleep -Seconds 7; }"
```
4. Wait until metrics are collected (~1 minute)
5. Execute command `kubectl top pod` and `kubectl top node`
6. Pods have in total more cpu usage than node.

**Expected behavior**
Node should report more cpu usage than its pods in total

**Screenshots**
![image](https://github.com/Azure/AKS/assets/50938720/8886828b-f62d-4273-96db-dd996be1a9de)
(The pods from the left are assigned to the node from the right, three kube-system pods are not included, each generates aroung 100m)

**Environment (please complete the following information):**
- Node image version: AKSWindows-2022-containerd-20348.2113.231115 or AKSWindows-2019-containerd-17763.5122.231115
- Output of `kubectl version -o=yaml`
```yaml
clientVersion:
  buildDate: "2023-09-13T09:35:49Z"
  compiler: gc
  gitCommit: 89a4ea3e1e4ddd7f7572286090359983e0387b2f
  gitTreeState: clean
  gitVersion: v1.28.2
  goVersion: go1.20.8
  major: "1"
  minor: "28"
  platform: windows/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2023-10-19T00:14:21Z"
  compiler: gc
  gitCommit: 07a61d861519c45ef5c89bc22dda289328f29343
  gitTreeState: clean
  gitVersion: v1.27.7
  goVersion: go1.20.10
  major: "1"
  minor: "27"
  platform: linux/amd64
```

**Additional context**
The problem has appeared after upgrading aks cluster from 1.26.10 to 1.27.7.

**Comment by BrunoJuchli** [comment]
This is reported as fixed in Kubernetes 1.29.3:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#v1293

aks 1.29.4 is available - so updating to that should fix the issue.

I think it's also been backported to older versions of kubernetes, but I haven't checked the release notes.

I guess this issue can therefore be closed?

**Comment by den4md** [comment]
@BrunoJuchli, thank you for the update!
I have upgraded control plane of the cluster to v1.29.5 (currently it's the latest 1.29 version) and created one B2s Win19 node with base image "AKSWindows-2019-containerd-17763.5936.240621". It gave the same results - CPU metrics of the node were lower than expected. The CPU% did not increase over 10%, even when the node was clearly overloaded (see examples). Old nodepools that were upgraded from 1.27.7 to 1.29.5 also suffer from the issue.

Example Nr.1 (node is overloaded - any operation with pods is extremely slow): CPU% is 10%, should be 100%.
![image](https://github.com/user-attachments/assets/f5f22618-905d-4bdc-952c-06d391874b5c)

Example Nr.2 (only one of two cores is overloaded): CPU% is 5%, should be 50%
![image](https://github.com/user-attachments/assets/d0dcbb1a-4a14-454e-a425-e35bf746d4cf)

Example Nr.3 (node is normally loaded): CPU% is 5%, should be around 50%
![image](https://github.com/user-attachments/assets/5cad3571-058e-401c-8cfa-513a4d7b1066)

**Comment by den4md** [comment]
As of AKS v1.32.4 the issue still persist. New bugticket was created - https://github.com/kubernetes/kubernetes/issues/131210

**Comment by sjwaight** [comment]
I've removed the retired Kubernetes version from the bug title as this issue seems to persist on supported Kubernetes version. It also looks to be upstream, and not AKS specific, but I'll leave this open.

**Comment by julia-yin** [comment]
Hi @den4md, looks like this issue has been open for a while. Are you still experiencing this issue?

**Comment by den4md** [comment]
Hi @julia-yin,
The behavior still persists. Tested it right now: kubernetes v1.35.3, Win2022, D8_v5.

Azure VMSS metrics show `36%` and `29%`:
<img width="279" height="292" alt="Image" src="https://github.com/user-attachments/assets/38a8d003-be6d-4ab3-bb67-3e4b84b7fcb8" />

kubectl top node shows `3%` and `2%`:
<img width="720" height="169" alt="Image" src="https://github.com/user-attachments/assets/920c6015-aa2f-4ab2-b51b-2e3b50077d4e" />
