### ISSUE TITLE
[Feature] Support for excluding AKS node pools from Azure LoadBalancer

### ISSUE THREAD

**Issue by kszyntar** [Azure/AKS#4167]
Currently there is no supported option to exclude AKS node pools from Azure LoadBalancer. As a result, regardless of how node pools are shaped, all nodes are added to the Load balancer. Depending on externalTrafficPolicy on the cluster, this either results in extra traffic hops or failed health checks.

**Describe the solution you'd like**
A clean way to remove a given AKS node pool from Azure LoadBalancer - either by explicit support in AKS API or with standard k8s label _exclude-from-external-load-balancers_
It is acceptable if this support comes with certain limitations - e.g. has a NAT Gateway for outbound as a prerequisite.

**Describe alternatives you've considered**
Standard method for doing so would be with labeling a node with _node.kubernetes.io/exclude-from-external-load-balancers=true_ - but as mentioned [here](https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#limitations) it is not supported with AKS (implying - label works only with self-managed k8s). There is no alternative way to accomplish this currently.

**Additional context**
Such issue has already been mentioned: https://github.com/Azure/AKS/issues/3545 but resulted only in a documentation update.

**Comment by treyhendon** [comment]
This is something that our organization is extremely interested as well.

**Comment by kevinharing** [comment]
I noticed this new feature. Is it possible to implement now in AKS?

https://azure.microsoft.com/en-us/updates/public-preview-azure-load-balancer-now-supports-admin-state/

**Comment by mailbox171** [comment]
Hello,
this is VITAL.
This property cannot be skipped.

**Comment by mailbox171** [comment]
Hello, I want to reiterate my plea. This feature cannot wait any longer.

I have large node pools with autoscaling and SPOT VMs. The situation is very .. dynamic, and I get occasional connection reset, which in the grpc world are real DISASTERS.

I tried externalTrafficPolicy: Local, but it has real bugs. Any update to the situation, topology, .. it breaks, and the workaraound is update the service to eTP: Cluster


Please help!!!

**Comment by philwelz** [comment]
@chasewilson is this a feature that is coming or is this something that never will come ? I have customers who want to use this feature.

**Comment by nilo19** [comment]
Hi all, will create a pool with the k8s exclude label solve your problem?

**Comment by pavneeta** [comment]
Hi Everyone, 

We are currently working on the development of the feature that will allow a given nodepool from being excluded from the SLB's inbound backend-pool via a label on the node pool. We will share more details via release notes once the feature is complete. You can track the status via the public roadmap board -https://github.com/orgs/Azure/projects/685

**Comment by boomer41** [comment]
Still waiting for this.

**Comment by nilo19** [comment]
I think we support node label `exclude-from-external-load-balancers` in aks. Can you give it a try?

**Comment by boomer41** [comment]
Do you have a piece of documentation concerning this label? Thank you.

**Comment by nbwdk** [comment]
@pavneeta - any update on this? This feature is very important for us.

**Comment by swgriffith** [comment]
This is supported via the exclude-from-external-load-balancers option noted above. I updated the docs to include this setup:

https://learn.microsoft.com/en-us/azure/aks/configure-load-balancer-standard?tabs=create-cluster-ip-based%2Ccreate-cluster-managed-outbound-ips%2Ccreate-cluster-custom-ips%2Ccreate-cluster-custom-ip-prefixes%2Ccreate-cluster-outbound-ports-ips%2Ccreate-cluster-idle-timeout#exclude-node-pool-from-load-balancer-backend-pool

**Comment by treyhendon** [comment]
I added `node.kubernetes.io/exclude-from-external-load-balancers=true` to all nodes except my Istio node pools this morning. The internal and external load balancers still show all nodes as unhealthy backend targets.

<img width="740" height="872" alt="Image" src="https://github.com/user-attachments/assets/b230af78-9152-4713-9b9b-dc72a47514b8" />
