### ISSUE TITLE
[BUG] Retina agent crashed

### ISSUE THREAD

**Issue by oleksii-goi** [Azure/AKS#4568]
**Describe the bug**
After enabling advanced network observability on our AKS clusters (https://learn.microsoft.com/en-us/azure/aks/advanced-network-observability-bring-your-own-cli?tabs=non-cilium) retina-agents pods crashed with the error: "Reason: OOMKilled - exit code: 137"
Currently memory limit configuration is 700Mi, but looks like it is not enough.

**To Reproduce**
1. Enable advanced network observability (https://learn.microsoft.com/en-us/azure/aks/advanced-network-observability-bring-your-own-cli?tabs=non-cilium)
2. After some time, check retina-agent pod events

**Expected behavior**
Pod should not restart with OOM

**Environment (please complete the following information):**
 -  Node image version: AKSAzureLinux-V2gen2-202407.29.0
 - Kubernetes version: 1.29.7
 - Retina agent image: mcr.microsoft.com/containernetworking/retina-agent-enterprise:v0.0.9

**Comment by vakalapa** [comment]
We are releasing a new version v0.1.0, that should solve this OOM issue. 

It should have reached all regions by now.

**Comment by oleksii-goi** [comment]
Hello Vaka

> We are releasing a new version v0.1.0, that should solve this OOM issue.
> 
> It should have reached all regions by now.

I see, that there is new image deployed (mcr.microsoft.com/containernetworking/retina-agent-enterprise:v0.1.0) but the issue is still there. Retina agent pods are still terminating with the error: " Reason:Reason: OOMKilled - exit code: 137"

**Comment by vakalapa** [comment]
@oleksii-goi  can you please email some basic cluster details like rg/cluster name fqdn to `vakr@microsoft.com`

**Comment by rahulrai-in** [comment]
@vakalapa following up on the issue.

**Comment by oleksii-goi** [comment]
Can we get an update please? The pods are still crashing alongside with hubble-relay pod

**Comment by snguyen64** [comment]
@oleksii-goi 
We have a new release, and changes planned that is expected to address the issue. However, due to CCOA, the release may be delayed until mid-January. While pods are restarting, the data remains accurate, though the metrics and counters are reset on retina agent restarts. 
In the interim, we can increase the memory limit to help mitigate the OOM kills. Would this solution be acceptable?

**Comment by oleksii-goi** [comment]
> [@oleksii-goi](https://github.com/oleksii-goi) We have a new release, and changes planned that is expected to address the issue. However, due to CCOA, the release may be delayed until mid-January. While pods are restarting, the data remains accurate, though the metrics and counters are reset on retina agent restarts. In the interim, we can increase the memory limit to help mitigate the OOM kills. Would this solution be acceptable?

Yes please, memory increase should help. 
How it will be done? Do we need to configure it on our side? Or you can do it from your side?

**Comment by snguyen64** [comment]
> > [@oleksii-goi](https://github.com/oleksii-goi) We have a new release, and changes planned that is expected to address the issue. However, due to CCOA, the release may be delayed until mid-January. While pods are restarting, the data remains accurate, though the metrics and counters are reset on retina agent restarts. In the interim, we can increase the memory limit to help mitigate the OOM kills. Would this solution be acceptable?
> 
> Yes please, memory increase should help. How it will be done? Do we need to configure it on our side? Or you can do it from your side?

You should be able to scale retina pods with VPA https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler

**Comment by snguyen64** [comment]
To give more information,
VPA can be used to scale retina pods with your own limits, we allow this for our addon. 
You can enable VPA through azure cli mentioned in above link. It is recommended to enable auto scale cluster feature or there could not be enough resources to scale the pod. Once VPA is enabled, VPA will read the VerticalPodAutoscaler CRs and set the memory/cpu limits.
This is an example of a CR that you may edit and apply to the cluster to update the limits of retina containers
```
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: retina-agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: retina-agent
  updatePolicy:
    updateMode: Initial
  resourcePolicy:
    containerPolicies:
      - containerName: retina
        maxAllowed:
          cpu: 1
          memory: 800Mi
        minAllowed:
          cpu: 100m
          memory: 100Mi
```
This is an example, and you may configure the limits to fit your needs. 
For example, you can update the update policy to something else instead of initial or auto. https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/docs/quickstart.md
