### ISSUE TITLE
DNS lookup timeouts

### ISSUE THREAD

**Issue by juan-lee** [Azure/AKS#667]
**Symptoms**
Outbound requests from pods can see a 5 second delay during DNS lookups. This is known to impact containers based off of the alpine image.

**Root Cause**
https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts

**Workaround**
Add the following to your impacted pod's manifest.
```
postStart:
  exec:
    command:
    - /bin/sh
    - -c
    - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
```

**What is single-request-reopen?**
``` 
single-request-reopen (since glibc 2.9)
  Sets RES_SNGLKUPREOP in _res.options.  The resolver
  uses the same socket for the A and AAAA requests.  Some
  hardware mistakenly sends back only one reply.  When
  that happens the client system will sit and wait for
  the second reply.  Turning this option on changes this
  behavior so that if two requests from the same port are
  not handled correctly it will close the socket and open
  a new one before sending the second request.
```

**Comment by devteng** [comment]
FYI, I have not testing this personally -- this supposedly will not work for Alpine based containers since MUSL lib that Alpine uses does not support this option.

https://github.com/kubernetes/kubernetes/issues/62628#issuecomment-389341878

**Comment by epoyraz** [comment]
We had the same issue using alpine image.
i would recommend to read this: https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/

We changed our base image to jessie-slim and added this to the pod manifest.
`dnsConfig:
  options:
    - name: single-request-reopen`
more details :https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

i think it is a cleaner solution than adding a postStart hook.

**Comment by timwebster9** [comment]
I'm not sure what to think about this.  Is the advice going to be: 'you can't run Alpine and need to customise DNS' if you expect proper DNS performance?

Could someone from Microsoft weigh in here?

**Comment by AXington** [comment]
This also works, and it works on alpine pods:

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
service/networking/custom-dns.yaml 
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: nginx
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.2.3.4
    searches:
      - ns1.svc.cluster.local
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0

**Comment by wutingbupt** [comment]
@AXington Your solution reduces the delay from 5 seconds to 2.5 :), but still not fully work.

**Comment by wutingbupt** [comment]
@juan-lee your workaround didn't work perfectly for the alpine based images, any better idea?

**Comment by juan-lee** [comment]
> @juan-lee your workaround didn't work perfectly for the alpine based images, any better idea?

My understanding is that we've rolled the fix out during this week's release. You will have to upgrade your cluster to a newer version of k8s to get the changes.

**Comment by wutingbupt** [comment]
Thanks very much, @juan-lee, I will let you know how does it work.
Br,
Tim

**Comment by wutingbupt** [comment]
@juan-lee The 1.11.4 solves this problem, thanks for your help.

Br,
Tim

**Comment by motarski** [comment]
I checked official [change log](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#changelog-since-v1113) can't find specific change that addresses this bug in the change log, but amazingly the upgrade seems to fix this issue for our AKS cluster. I hope it will not come back on next version bump.

**Comment by motarski** [comment]
Ok I see, thanks for explanation@juan-lee

**Comment by timwebster9** [comment]
@juan-lee is the fix only present in the new 'MobyImage' that you have to register for, or is it present in all 1.11.4 images?

**Comment by weinong** [comment]
Hi people!
As it stands today, all new VMs (through new cluster, scale, or upgrade) have the kernel fix '"netfilter: nf_conntrack: resolve clash for matching conntracks" fixes the 1st race (accepted).` described in https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts

Thanks

**Comment by jeffmartinxyz** [comment]
@weinong any info on when the second race will be addressed?

**Comment by kim0** [comment]
I just hit this, and `single-request-reopen` does seem to make it go away! This is on a recent fresh `1.13.5` aks cluster. Not sure why the DNS server gives the wrong answer to begin with. Is this a coredns issue ? 
Thanks @juan-lee for the work-around 👍

**Comment by kim0** [comment]
Hi @weinong .. I deployed a cluster a few days back, and still hitting this. So I think it's still not fixed. Is there any update when a fix is expected to land. 
Also taking a chance and pinging @jnoller

**Comment by tapanhalani** [comment]
Hi people. Is this issue fixed with kubernetes 1.13.5? I wanted to upgrade my AKS cluster to the said version, but I am using multiple deployments with alpine-based images.

**Comment by jemag** [comment]
Still seeing the issue with kernel-version 4.15.0-1063-azure

**Comment by Vandersteen** [comment]
I also am seeing this issue in kernel version 4.15.0-1060-azure

**Comment by juan-lee** [comment]
@jemag @Vandersteen Recently I've seen DNS timeouts being caused by high resource usage on the nodes where the coredns pods reside. Could either of you check your monitoring and see how saturated your CPU, memory, and disk are?

**Comment by jemag** [comment]
@juan-lee I have  replicated this problem under various loads. Currently with all nodes under 18% cpu usage and memory at around 70% for each node the problem still happens intermittently. Disk usage is extremely low.

**Comment by Vandersteen** [comment]
@juan-lee I have replicated this on 2 different clusters. 1 has 40% cpu usage & 60% memory usage. The other one has 20% cpu usage and 42% memory usage.

**Comment by juan-lee** [comment]
@jemag @Vandersteen we are looking into it. By chance are your clusters using azure cni? I'm only able to reproduce the issue with azure cni clusters.

**Comment by jemag** [comment]
@juan-lee mine are indeed using azure cni

**Comment by Vandersteen** [comment]
@juan-lee Yes we are using azure cni

**Comment by juan-lee** [comment]
We are still working to get to the bottom of this issue. In the meantime, adding the following to your specs in most cases can help.

```
dnsConfig:  
  options:  
    - name: single-request-reopen
```

**Comment by guitmz** [comment]
This started to happen for me when we upgraded the cluster to v.1.14 (from 1.13). We had the same problem a year ago and it was fixed after the kernel was patched with the mitigations from https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts

is there a way we can run coredns in AKS as daemonset to try to fix this (at least try)? We need azure cni and we cant use `single-request-reopen` for all pods because some are alpine based

**Comment by jnoller** [comment]
Please also see this issue for intermittent nodenotready, DNS latency and other crashed related to system load: #1373

**Comment by kwaazaar** [comment]
> We are still working to get to the bottom of this issue. In the meantime, adding the following to your specs in most cases can help.
> 
> ```
> dnsConfig:  
>   options:  
>     - name: single-request-reopen
> ```

I tried this, but keep getting this issue. I have a container doing a curl statement in a loop with a 2 second pause in between attempt and get it about once every 20 attempts. I seems to happen on 3 clusters (OT, ACC and PROD). On those last two this seems to help pretty well. On the OT-cluster (1.16.9) it does not. All clusters are using Azure CNI and use private networking and a VPN connection to on-prem DNS-servers.

**Comment by aviramha** [comment]
Will microsoft ever solve this?

**Comment by neil-south** [comment]
This is now effecting us. the workaround
```
dnsConfig:  
  options:  
    - name: single-request-reopen
```
seems to work, but obviously this is effecting lots of people (most of which wont even realise), and needs sorting!

Ive even tried creating a new v1.19 AKS cluster, and using the official `mcr.microsoft.com/dotnet/core/aspnet:3.1` docker base image (as of 29/9/2020) and the issue is still present.

**Comment by davesmits** [comment]
We used the dnsCOnfig work around and initially it didnt work for us. It turned out that it only works with the non-alpine images.

**Comment by sikri-eic** [comment]
Is there a solution/workaround for this issue for Alpine based images? We tried `dnsPolicy: Default` to no avail. We are also using Azure CNI.

Kubernetes cluster version: `1.18.8`
OS Image: `Ubuntu 16.04.7 LTS`

A newer version of OS image (18.04) has been deployed very recently, would it help to upgrade?

**Comment by timja** [comment]
@sikri-eic deploying nodelocaldns fixed it for us.
18.04 didn't solve it in our case

**Comment by sikri-eic** [comment]
@timja Thank you for the prompt response. I will take a look at `nodelocaldns`. The documentation sounds like it may actually address this problem.

**Comment by Vandersteen** [comment]
@timja Did you have to do anything special to install nodelocaldns on aks ? Seems like you need to mess around with IPtables or something

**Comment by timja** [comment]
It depends if you're using kubenet or azure cni,

kubenet works with just the standard config,

azure cni:

add the -setupebtables flag

ref:
https://github.com/Azure/AKS/issues/1642

example config for azure cni (note it took months for a release after our changes so we're using a forked image but looks like upstream have released now):
https://github.com/hmcts/cnp-flux-config/blob/master/k8s/namespaces/kube-system/nodelocaldns/nodelocaldns.yaml

**Comment by curtdept** [comment]
Here is a version for AKS, runs on everything except virtual node.

https://github.com/curtdept/aks_nodelocaldns/blob/main/nodelocaldns.yaml

**Comment by palma21** [comment]
Marking these as duplicate/known-issue and adding the in-progress feature for it as well as well as @curtdept current workaround (thanks!)

https://github.com/curtdept/aks_nodelocaldns/blob/main/nodelocaldns.yaml

https://github.com/Azure/AKS/issues/1492
