### ISSUE TITLE
can't update CoreDNS ConfigMap

### ISSUE THREAD

**Issue by agashkov** [Azure/AKS#811]
I can't configure the CoreDNS configmap.
After the change in some time (60s) it returns to its original state. 
This is due to the use of the Reconcile mode in the cofigmap:

apiVersion: v1
kind: ConfigMap
metadata:
name: coredns
namespace: kube-system
labels:
addonmanager.kubernetes.io/mode: Reconcile

My AKS cluster is new without updates (version 1.12.4 kubernetes)

**Comment by jnoller** [comment]
This should be resolved with the hotfix rolling out to all regions as we speak, please see:

https://github.com/Azure/AKS/releases/tag/2019-02-07

**Comment by jnoller** [comment]
Hotfix rolled out

**Comment by liambarnett** [comment]
This is still an issue in 1.12.5. I created my cluster late last week. I have tried deleting the pod after updating the config map but it still reverts the changes.

**Comment by jnoller** [comment]
@liambarnett please open a tech support issue in the azure portal - we have tests validating this, and user data showing this is functioning, so opening a ticket with the symptoms and sub information will help us root cause

**Comment by fhoy** [comment]
Having been in contact with MS support about the same issue, we finally noticed that the release notes (https://github.com/Azure/AKS/releases/tag/2019-02-07) apparently mentions editing a _separate_ `ConfigMap`, `coredns-custom`. I have not had the opportunity to test this yet, though.

Furthermore, MS support said that the hotfix "was designed to affect newly created clusters", so existing clusters would not be affected.

**Comment by jnoller** [comment]
@fhoy Some corrections (and I will reach out to support to figure out where the invalid guidance came from)

- Yes, the release notes show the new format and note that it is not backwards compatible with kube-dns.
- Existing clusters that upgrades from versions prior to 1.12 were manually repaired by engineering, if you have a cluster exhibiting the coreDNS/kube-dns conflicts, please file a ticket and link to this comment to flag it so that support knows to escalate to repair.

**Comment by jnoller** [comment]
Please take note: You can not change the kube-dns config map on clusters running the CoreDNS system - please see https://github.com/Azure/AKS/releases/tag/2019-02-07 and also: Custom settings should be added to coredns-custom configmap and not the coredns configmap otherwise the changes will be overwritten

**Comment by toyota790** [comment]
The ConfigMap of the coredns-custom has some restrictions on the format. You can refer to it as below. I just knew about it from the Microsoft support engineer. I hope it will be helpful for you.

The example will create a ConfigMap for the CoreDNS, which want to add a rewrite rule by leveraging [rewrite](https://coredns.io/plugins/rewrite/) plugin of CoreDNS.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: | # you may select any name here, but it must end with the .server file extension
    <domain to be rewritten>.com:53 {
        errors
        cache 30
        rewrite name substring abc.com default.svc.cluster.local
        proxy .  /etc/resolv.conf # you can redirect this to a specific DNS server such as 10.0.0.10 
    }
```

It also needs to be careful about the [order of precedence]( https://github.com/coredns/coredns/blob/master/plugin.cfg
) for the plugins of CoreDNS.
